default: &default 
  adapter: postgresql 
  username: alexisrabagocarvajal
  password: Monitos2?
  host: localhost 

development: 
  <<: *default 
  database: sesa_development 

test:
  <<: *default 
  database: sesa_test 

production: 
  <<: *default 
  database: sesa_production
