# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!(email: 'admin@hotmail.com', password: 'password', password_confirmation: 'password')
Clinic.create!(name:"C.S.U.1", address:"")
Clinic.create!(name:"C.S.U.2", address:"")
Clinic.create!(name:"C.S.U.3", address:"")
Clinic.create!(name:"C.S.U.4", address:"")
Clinic.create!(name:"C.S.U.6", address:"")
Clinic.create!(name:"C.S.U.7", address:"")
Clinic.create!(name:"ALLENDE", address:"")
Clinic.create!(name:"ALTOS DE SEVILLA", address:"")
Clinic.create!(name:"ALVARO OBREGON", address:"")
Clinic.create!(name:"ANDRES QUINTANA ROO", address:"")
Clinic.create!(name:"AVILA CAMACHO", address:"")
Clinic.create!(name:"BLANCA FLOR", address:"")
Clinic.create!(name:"BUENA ESPERANZA", address:"")
Clinic.create!(name:"BUENA VISTA", address:"")
Clinic.create!(name:"UMM CEREQUE", address:"")
Clinic.create!(name:"UMM GOLONDRINA", address:"")
Clinic.create!(name:"UMM JABALI", address:"")
Clinic.create!(name:"UMM MANATI", address:"")
Clinic.create!(name:"UMM PELICANO", address:"")
Clinic.create!(name:"UMM TIGRILLO", address:"")
Clinic.create!(name:"UMM VENADO", address:"")
Clinic.create!(name:"CAANLUMIL", address:"")
Clinic.create!(name:"CACAO", address:"")
Clinic.create!(name:"CALDERITAS", address:"")
Clinic.create!(name:"CALDERON ", address:"")
Clinic.create!(name:"CAOBAS", address:"")
Clinic.create!(name:"CAPACIT", address:"")
Clinic.create!(name:"CHACCHOBEN", address:"")
Clinic.create!(name:"COCOYOL", address:"")
Clinic.create!(name:"CRECENCIO REJON ", address:"")
Clinic.create!(name:"DAVID GUSTAVO", address:"")
Clinic.create!(name:"DIVORCIADOS", address:"")
Clinic.create!(name:"DOS AGUADAS", address:"")
Clinic.create!(name:"EL TESORO", address:"")
Clinic.create!(name:"FELIPE ANGELES", address:"")
Clinic.create!(name:"FRANCISCO J. MUJICA", address:"")
Clinic.create!(name:"FRANCISCO VILLA", address:"")
Clinic.create!(name:"HOSPITAL GENERAL DE CHETUMAL", address:"")
Clinic.create!(name:"HOSPITAL INTEGRAL DE BACALAR", address:"")
Clinic.create!(name:"HOSPITAL MATERNO INFANTIL MORELOS", address:"")
Clinic.create!(name:"HABITAD I", address:"")
Clinic.create!(name:"HUATUSCO", address:"")
Clinic.create!(name:"HUAY-PIX", address:"")
Clinic.create!(name:"JUAN SARABIA", address:"")
Clinic.create!(name:"KUCHUMATAN", address:"")
Clinic.create!(name:"LA LAGUNA", address:"")
Clinic.create!(name:"LA LIBERTAD", address:"")
Clinic.create!(name:"LA PANTERA", address:"")
Clinic.create!(name:"LA UNION", address:"")
Clinic.create!(name:"LAZARO CARDENAS", address:"")
Clinic.create!(name:"LIMONES", address:"")
Clinic.create!(name:"LUIS ECHEVERRIA", address:"")
Clinic.create!(name:"MAHAHUAL", address:"")
Clinic.create!(name:"MARGARITA MAZA", address:"")
Clinic.create!(name:"MAYA BALAM", address:"")
Clinic.create!(name:"MELCHOR OCAMPO", address:"")
Clinic.create!(name:"MIGUEL ALEMAN", address:"")
Clinic.create!(name:"MOROCOY", address:"")
Clinic.create!(name:"NACHICOCOM", address:"")
Clinic.create!(name:"NICOLAS BRAVO", address:"")
Clinic.create!(name:"NUEVO BECAR", address:"")
Clinic.create!(name:"NUEVO JERUSALEM", address:"")
Clinic.create!(name:"NUEVO VERACRUZ", address:"")
Clinic.create!(name:"OTILIO MONTAÑO", address:"")
Clinic.create!(name:"PALMAR", address:"")
Clinic.create!(name:"PUCTE", address:"")
Clinic.create!(name:"RAMONAL", address:"")
Clinic.create!(name:"RAUDALES", address:"")
Clinic.create!(name:"REFORMA", address:"")
Clinic.create!(name:"RIO ESCONDIDO", address:"")
Clinic.create!(name:"RIO VERDE", address:"")
Clinic.create!(name:"ROJO GOMEZ", address:"")
Clinic.create!(name:"ROVIROSA", address:"")
Clinic.create!(name:"SABIDOS", address:"")
Clinic.create!(name:"SAN PEDRO PERALTA", address:"")
Clinic.create!(name:"SAN ROMAN", address:"")
Clinic.create!(name:"SERGIO BUTRON CASAS", address:"")
Clinic.create!(name:"SUBTENIENTE LOPEZ", address:"")
Clinic.create!(name:"OMAS GARRIDO", address:"")
Clinic.create!(name:"TRES GARANTIAS", address:"")
Clinic.create!(name:"UCUM", address:"")
Clinic.create!(name:"VALLE HERMOSO", address:"")
Clinic.create!(name:"XUL-HA", address:"")
Clinic.create!(name:"ZAMORA", address:"")
Clinic.create!(name:"CRÓNICOS", address:"")
Clinic.create!(name:"VIOLENCIA  INTRA", address:"")
Clinic.create!(name:"SALUD MENTAL", address:"")
Clinic.create!(name:"UNEME MAMA", address:"")
Clinic.create!(name:"ADICCIONES", address:"")
Clinic.create!(name:"H. G. CHETUMAL", address:"")
Clinic.create!(name:"H.M.I. MORELOS", address:"")
Clinic.create!(name:"H. I. JOSE MARIA M", address:"")
Clinic.create!(name:"H.G. FELIPE CARRILLO P.", address:"")
Clinic.create!(name:"H.G. KUMATE", address:"")
Clinic.create!(name:"H.I. ISLA MUJE", address:"")
Clinic.create!(name:"H.G.  COZUMEL", address:"")
Clinic.create!(name:"H.G. PLAYA CARMEN", address:"")
Clinic.create!(name:"H.I. KANTUNILKIN", address:"")
Clinic.create!(name:"H.G.   O'HORAN", address:"")
Clinic.create!(name:"H.R. ALTA ESPEC.", address:"")
Clinic.create!(name:"IMSS", address:"")
Clinic.create!(name:"ISSSTE", address:"")
Clinic.create!(name:"OTROS", address:"")
Specialty.create!(name:"CIR. GENERAL", description:"")
Specialty.create!(name:"MED. INTERNA", description:"")
Specialty.create!(name:"GINECOBSTETRI", description:"")
Specialty.create!(name:"PEDIATRIA", description:"")
Specialty.create!(name:"URGENCIAS", description:"")
Specialty.create!(name:"RADIOLOGÍA", description:"")
Specialty.create!(name:"ULTRASONIDO", description:"")
Specialty.create!(name:"MAMOGRAFIA", description:"")
Specialty.create!(name:"LABORATORIO", description:"")
Specialty.create!(name:"TER. INTENSIVA", description:"")
Specialty.create!(name:"CARDIOLOGÍA", description:"")
Specialty.create!(name:"DISPLASIAS", description:"")
Specialty.create!(name:"UROLOGIA", description:"")
Specialty.create!(name:"NEFROLOGIA", description:"")
Specialty.create!(name:"TRAUMATOLOG", description:"")
Specialty.create!(name:"O.R.L.", description:"")
Specialty.create!(name:"DENTAL", description:"")
Specialty.create!(name:"MAXILOFACIAL", description:"")
Specialty.create!(name:"RECONSTRUCTIVA", description:"")
Specialty.create!(name:"PSICOLOGÍA", description:"")
Specialty.create!(name:"PSIQUIATRÍA", description:"")
Specialty.create!(name:"DERMATOLOGÍA", description:"")
Specialty.create!(name:"OFTALMOLOGÍA", description:"")
Specialty.create!(name:"NEUROLOGÍA", description:"")
Specialty.create!(name:"ONCOLOGÍA", description:"")
Specialty.create!(name:"OTRAS", description:"")